### ISSUE TITLE
Zdharma organisation has been delete

### ISSUE THREAD

**Issue by luong-komorebi** [alpha-baby/dotfiles#1]
More context over here https://github.com/zdharma-continuum/I_WANT_TO_HELP 

Could you check your local machine for possible copy of zsh-unique-id? This repo has 0 fork so it is really hard to find a copy of it and repost on @zdharma-continuum

**Comment by alpha-baby** [comment]
https://github.com/alpha-baby/zsh-unique-id

**Comment by alpha-baby** [comment]
Thank you for your work on open source @luong-komorebi

**Comment by alpha-baby** [comment]
https://github.com/alpha-baby/git-url

**Comment by luong-komorebi** [comment]
Thank you so much for assisting with these source codes. All should be now found in https://github.com/zdharma-continuum (you should opt for changing the upstream in your zsh config to this one, too)
